### ISSUE TITLE
Figure out how to make ball bounce around the screen

### ISSUE THREAD

**Issue by adil1508** [karanbhandari/Kaze#10]
We want to make sure that the ball can bounce around the screen and when it hits an edge, it bounces off at a different angle each time so that it doesn't just follow a single path each time

**Comment by e-luo** [comment]
ball gets faster after it hits a paddle, but slower if it hits other things

**Comment by adil1508** [comment]
Progress:

- Horizontal movement done. calculations are being done dynamically.

Todo: 
- cleanup horizontal
- code in vertical movement
