### ISSUE TITLE
develop mockup screens and source image files 

### ISSUE THREAD

**Issue by karanbhandari** [karanbhandari/Kaze#11]
work on the user flow as well

**Comment by adil1508** [comment]
Screens we need: 

- Opening splash screen
- Home screen (start game + user login) 
- Login screen (authentication screen) 
- A screen where we pick if we want single 
- A multiplayer gameplay screen (Similar to the twoplayer mockup we demo-ed)
- A 'finished game' screen. This might have game stats and/or say who won. Options to play again too
- A single player gameplay screen
- A build screen where a user can setup defence presets that they will use in the multiplayer game
- An invite player screen

**Comment by e-luo** [comment]
Add credits screen 
Design icon
