### ISSUE TITLE
Creating concrete brick classes

### ISSUE THREAD

**Issue by adil1508** [karanbhandari/Kaze#13]
- Classes that define brick objects
- Some properties we want
-- Different colors
-- hit method (decrease the brick health)
-- Detect that the brick has been hit 
-- change images depending on health
-- animations&sound (maybe? if time permits)

**Comment by karanbhandari** [comment]
<img width="352" alt="Screen Shot 2019-06-12 at 1 34 34 PM" src="https://user-images.githubusercontent.com/13277201/59373065-db53a600-8d16-11e9-8c48-c5e7e8eb1c9f.png">

**Comment by karanbhandari** [comment]
- RectF structure (private) to hold coordinates
- int hp: to termine color and visibility
- Color property
- Opacity
- drawMethod: draws RectF, Color and Opacity
- oninit: changes opacity and HP

if hp == 0:
    isVisible = false
